server:
  port: 8081

logging:
  level:
    org.springframework.web: DEBUG
    com.securedoc: DEBUG

spring:
  application:
    name: securedoc-backend
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/securedoc
    username: admin
    password: secretpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# Client configuration for Python Service
ai-service:
  url: http://localhost:8000
